# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='event_date',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='validation',
            name='outfit',
            field=models.CharField(max_length=700),
        ),
    ]
