# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_auto_20180328_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='event_type',
            field=models.CharField(max_length=250),
        ),
    ]
