# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-29 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_auto_20180328_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='outfit_image',
            field=models.FileField(blank=True, max_length=700, null=True, upload_to=b''),
        ),
    ]
