# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-01 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_validation_outfit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='tags',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='validation',
            name='outfit_image',
            field=models.FileField(blank=True, max_length=700, null=True, upload_to=''),
        ),
    ]
