# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_auto_20180401_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='tags',
        ),
        migrations.AlterField(
            model_name='validation',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestions.EventType'),
        ),
        migrations.DeleteModel(
            name='Outfit',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='tags',
            field=models.ManyToManyField(to='suggestions.EventTag'),
        ),
    ]
