# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0006_auto_20180401_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='event_type',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='feedback',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='outfit',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
