# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-04 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0007_auto_20180402_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_image', models.FileField(upload_to='')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestions.EventType')),
                ('image_tags', models.ManyToManyField(to='suggestions.ImageTag')),
            ],
        ),
        migrations.RemoveField(
            model_name='validation',
            name='outfit',
        ),
        migrations.AlterField(
            model_name='validation',
            name='event_date',
            field=models.DateTimeField(max_length=250),
        ),
    ]
