# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0008_auto_20180404_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='outfit',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='options',
            field=models.ManyToManyField(to='suggestions.SuggestionOption'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suggestions.EventType'),
        ),
    ]
