# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0009_auto_20180419_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='options',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='option_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_1', to='suggestions.SuggestionOption'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='option_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_2', to='suggestions.SuggestionOption'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='option_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_3', to='suggestions.SuggestionOption'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='option_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_4', to='suggestions.SuggestionOption'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='option_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_5', to='suggestions.SuggestionOption'),
        ),
    ]
