# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-25 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0010_auto_20180419_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, max_length=700, null=True, upload_to=b'')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestions.EventType')),
            ],
        ),
    ]
