# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0012_auto_20180425_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionoption',
            name='answer_image',
            field=models.FileField(blank=True, max_length=700, null=True, upload_to=b''),
        ),
    ]
