# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0013_auto_20180515_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionimages',
            name='image',
            field=models.FileField(blank=True, max_length=700, null=True, upload_to='/media/'),
        ),
        migrations.AlterField(
            model_name='suggestionoption',
            name='answer_image',
            field=models.FileField(blank=True, max_length=700, null=True, upload_to=''),
        ),
    ]
