# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0014_auto_20180515_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionimages',
            name='image',
            field=models.ImageField(blank=True, max_length=700, null=True, upload_to='/media/'),
        ),
    ]
