# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import suggestions.models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0017_auto_20180515_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='code_name',
            field=models.CharField(default=suggestions.models.x, max_length=250),
        ),
    ]
