# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField(choices=[(0, 'Black'), (1, 'Neutrals'), (2, 'Rainbow'), (3, 'Earth Tones')], verbose_name='If we opened your closet, what color palette would we mostly see?')),
                ('question_2', models.IntegerField(choices=[(0, 'Traditional'), (1, 'Sharp'), (2, 'Playful'), (3, 'Relaxed Tones')], verbose_name='How would your friends describe you?')),
                ('question_3', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Normal'), (2, 'One piece at a time'), (4, 'Quite adventurous')], verbose_name='How adventurous are you with your style?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
