# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-01 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180401_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='answer_image',
            field=models.FileField(upload_to=''),
        ),
    ]
