# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-01 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20180402_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option1', to='survey.Option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option2', to='survey.Option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option3', to='survey.Option'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option4', to='survey.Option'),
        ),
    ]
