# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180402_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_1', to='survey.Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_2', to='survey.Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_3', to='survey.Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_4', to='survey.Option'),
        ),
    ]
