# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-02 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20180402_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_description',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
