# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-02 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_option_option_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_description',
            field=models.CharField(default='default', max_length=250),
        ),
    ]
